TestTask/TestTask/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls'))

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) if settings.DEBUG else []

TestTask/mainapp/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from .views import *

urlpatterns = [
    path("login/", LoginUserView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path("registration/", register_user, name='registration'),
    path("", index, name='index'),
    path("profile-employer/", profile_employer, name='profile_employer'),
    path("profile-worker/", profile_worker, name='profile_worker'),
    path("exp-add/", exp_add, name='exp_add'),
    path('delete-exp/',delete_exp, name='delete_exp'),
    path('reset-password/', PasswordResetView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-password/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

TestTask/mainapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django_resized import ResizedImageField


# Create your models here.
class CatUser(models.Model):
    cat_user = models.CharField(max_length=15, verbose_name='Категория полльзователя')

    class Meta:
        verbose_name = 'Категория пользователей'
        verbose_name_plural = 'Категории пользователей'

    def __str__(self):
        return self.cat_user


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    cat_user = models.ForeignKey(CatUser, on_delete=models.PROTECT)
    photo = ResizedImageField(size=[300, 300], upload_to='avatars', default='def_avatar.jpg', verbose_name='Фото '
                                                                                                           'профиля')

    class Meta:
        verbose_name = 'Профиль пользователя'
        verbose_name_plural = 'Профили пользователей'


class Experience(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    place_work = models.CharField(max_length=20, verbose_name='Место работы')
    position = models.CharField(max_length=20, verbose_name='Должность')
    time_start = models.DateField(verbose_name='Работал с')
    time_end = models.DateField(verbose_name='Работал по')

    class Meta:
        verbose_name = 'Опыт'
        verbose_name_plural = 'Опыт'

TestTask/mainapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import Experience, UserProfile, CatUser


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', )
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput())


class RegisterUserFrom(UserCreationForm):
    first_name = forms.CharField(label='Имя')
    last_name = forms.CharField(label='Фамилия')
    username = forms.CharField(label='Логин', )
    email = forms.EmailField(label='Email', )
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class UserProfileForm(forms.ModelForm):
    cat_user = forms.ModelChoiceField(label='Кто вы', queryset=CatUser.objects.all() )
    photo = forms.ImageField(label='Фото профиля', required=False)

    class Meta:
        model = UserProfile
        fields = ('cat_user', 'photo')


class ChangeUserInfoForm(forms.ModelForm):
    first_name = forms.CharField(label='Имя', required=False)
    last_name = forms.CharField(label='Фамилия', required=False)
    email = forms.EmailField(label='Email', required=False)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ChangeUserProfileForm(forms.ModelForm):
    photo = forms.ImageField(label='Фото профиля', required=False)
    class Meta:
        model = UserProfile
        fields = ('photo',)


class ExperienceForm(forms.ModelForm):
    place_work = forms.CharField(label='Место работы', )
    position = forms.CharField(label='Должность', )
    time_start = forms.DateField(label='Работал/а с...', widget=forms.widgets.DateInput(
        attrs={'type': 'date', 'placeholder': 'dd-mm-yyyy(DOB)'}))
    time_end = forms.DateField(label='Работал/а по...', widget=forms.widgets.DateInput(
        attrs={'type': 'date', 'placeholder': 'dd-mm-yyyy(DOB)'}))

    class Meta:
        model = Experience
        fields = ('place_work', 'position', 'time_start', 'time_end')

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("time_start")
        finish_date = cleaned_data.get("time_end")
        if finish_date and start_date and finish_date <= start_date:
            raise ValidationError("Дата окончания не может быть меньше или равной дате начала.")

TestTask/mainapp/views.py
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .forms import *
from .models import *
from .serv import change_user_info
from django.contrib.auth.views import LoginView


# Create your views here.
def index(request):
    if request.user.is_authenticated:
        user_cat = UserProfile.objects.get(user_id=request.user.pk)

        context = {'cat': user_cat.cat_user_id}
        return render(request, 'mainapp/index.html', context)
    return render(request, 'mainapp/index.html')


def register_user(request):
    user_form = RegisterUserFrom()
    profile_form = UserProfileForm()
    if request.method == 'POST':
        user_form = RegisterUserFrom(request.POST)
        profile_form = UserProfileForm(request.POST, request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user_id = user.id
            profile_form.save()
            return redirect(reverse_lazy('login'))
    context = {'user_form': user_form, 'profile_form': profile_form, 'title': 'Регистрация'}
    return render(request, 'mainapp/registration.html', context)


class LoginUserView(LoginView):
    form_class = LoginUserForm
    template_name = 'mainapp/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Авторизация'
        return context

    def get_success_url(self):
        return reverse_lazy('index')


def logout_view(request):
    logout(request)
    return redirect('index')


def profile_employer(request):
    user_info = User.objects.get(pk=request.user.pk)
    user_profile = UserProfile.objects.get(user_id=request.user.pk)
    change_user_form = ChangeUserInfoForm()
    change_profile_form = ChangeUserProfileForm()
    change_user_info(request)
    context = {'user_info': user_info, 'user_profile': user_profile, 'title': 'Профиль',
               'change_user_form': change_user_form, 'change_profile_form': change_profile_form}
    return render(request, 'mainapp/profile_employer.html', context)


def profile_worker(request):
    user_info = User.objects.get(pk=request.user.pk)
    user_profile = UserProfile.objects.get(user_id=request.user.pk)
    user_exp = Experience.objects.filter(user_id=request.user.pk)
    change_user_form = ChangeUserInfoForm()
    change_profile_form = ChangeUserProfileForm()
    change_user_info(request)
    context = {'user_info': user_info, 'user_profile': user_profile, 'title': 'Профиль', 'user_exp': user_exp,
               'change_user_form': change_user_form, 'change_profile_form': change_profile_form, }
    return render(request, 'mainapp/profile_worker.html', context)


def exp_add(request):
    user_exp_form = ExperienceForm()
    if request.method == 'POST':
        user_exp_form = ExperienceForm(request.POST, )
        if user_exp_form.is_valid():
            user = request.user.pk
            exp = user_exp_form.save(commit=False)
            exp.user_id = user
            user_exp_form.save()
    context = {'user_exp_form': user_exp_form, 'title': 'Опыт работы'}
    return render(request, 'mainapp/exp_add.html', context)


def delete_exp(request):
    if request.method == 'POST':
        record_id = request.POST.get('record_id')
        Experience.objects.filter(id=record_id).delete()
    return redirect('profile_worker')

TestTask/mainapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="{% static 'TestTask/jquery-3.7.1.min.js' %}" defer></script>
    <script src="{% static 'TestTask/scripts.js' %}" defer></script>
    <link rel="stylesheet", type="text/css", href="{% static 'TestTask/style.css' %}">
</head>
<body>
<div class="wrapper">
    <div class="navbar">
    <div class="menu">
        <a href="{% url 'index' %}">Дизайн</a>
        <a href="{% url 'index' %}">Разработка</a>
        <a href="{% url 'index' %}">Тексты и перевод</a>
        <a href="{% url 'index' %}">Соцсети и реклама</a>
        <a href="{% url 'index' %}">SEO и реклама</a>
    </div>
    <div class="auth">
        {% if request.user.is_authenticated %}
            {% if cat == 1 %}
                <a href="{% url 'profile_employer' %}">Профиль</a>
            {% else %}
                <a href="{% url 'profile_worker' %}">Профиль</a>
            {% endif %}
        <a href="{% url 'logout' %}">Выход</a>
        {% else %}
         <a href="{% url 'login' %}">Вход</a>
         <a href="{% url 'registration' %}">Регистрация</a>
        {% endif %}
    </div>
    </div>
{% block content %}
{% endblock %}
</div>

</body>
</html>

TestTask/mainapp/templates/profile_base.html
{% extends 'base.html' %}
{% block content %}
<div id="profile">
<div class="maininfo">
    <h1>{{ title }}</h1>
    <img src="{{ user_profile.photo.url }}">
    <p>{{ user_profile.cat_user }}</p>
    <p>{{ user_info.email }}</p>
    <p>{{ user_info.first_name }} {{ user_info.last_name }}</p>
    <div>
    <button id="changeInfo" type="submit">Изменить информацию</button>
    </div>
<div id="change_form" aria-hidden="true">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ change_user_form.non_field_errors }}
    <div class="form-group" >
        {{ user_info.place_work.errors }}
        <label for="{{ change_user_form.first_name.id_for_label }}">Имя:</label>
        {{ change_user_form.first_name }}
    </div>
    <div class="form-group">
        {{ user_info.position.errors }}
        <label for="{{ change_user_form.last_name.id_for_label }}">Фамилия:</label>
        {{ change_user_form.last_name }}
    </div>
    <div class="form-group">
        {{ user_info.time_start.errors }}
        <label for="{{ change_user_form.email.id_for_label }}">Почта:</label>
        {{ change_user_form.email }}
    </div>
    <div class="form-group">
        {{ change_user_form.photo.errors }}
        <label for="{{ change_user_form.photo.id_for_label }}">Фото</label>
        {{ change_user_form.photo }}
        <input type="file" name="photo" id="id_photo" accept="image/*">
    </div>
    <button type="submit">Сохранить</button>
</form>
    <button class="inputbox" id="out" type="submit">Отмена</button>

</div>
</div>
{% block for_child %}
{% endblock %}
</div>
{% endblock %}